output "id1" {
  value = random_uuid.id1.result
}
output "id2" {
  value = random_uuid.id2.result

}
output "id3" {
  value = random_uuid.id3.result

}

output "id4" {
  value = random_uuid.id4.result

}
output "id5" {
  value = random_uuid.id5.result
}

output "id6" {
  value = random_uuid.id6.result

}
output "id7" {
  value = random_uuid.id7.result

}
output "order1" {
  value = random_integer.order1.result

}
output "order2" {
  value = random_integer.order1.result

}
resource "random_pet" "my-pet" {

  length    = var.length
}

output "pet-name" {

  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
  filename = "/root/message.txt"
  content = "Welcome to Kodekloud."
}

